### ISSUE TITLE
PHP 7 error

### ISSUE THREAD

**Issue by koganei** [bajpangosh/Nextcloud-With-Cloudflare-SSL-Easy-Install-script#1]
Hi, I've just tried running your script, following this video tutorial: https://www.youtube.com/watch?v=7DRsNNWs1HE

I run into the following issue when running the script:

> ...
> Nginx server installation completed
> lets install php 7.0 and modules
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Note, selecting 'php7.0-remctl' for regex 'php7.0'
> Note, selecting 'php7.0-common' for regex 'php7.0'
> Note, selecting 'php-remctl' instead of 'php7.0-remctl'
> E: Unable to locate package php7.0-fpm
> E: Couldn't find any package by glob 'php7.0-fpm'
> E: Couldn't find any package by regex 'php7.0-fpm'
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Package php7.0-common is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Unable to locate package php7.0-curl
> E: Couldn't find any package by glob 'php7.0-curl'
> E: Couldn't find any package by regex 'php7.0-curl'
> E: Unable to locate package php7.0-gd
> E: Couldn't find any package by glob 'php7.0-gd'
> E: Couldn't find any package by regex 'php7.0-gd'
> E: Unable to locate package php7.0-imap
> E: Couldn't find any package by glob 'php7.0-imap'
> E: Couldn't find any package by regex 'php7.0-imap'
> E: Unable to locate package php7.0-mcrypt
> E: Couldn't find any package by glob 'php7.0-mcrypt'
> E: Couldn't find any package by regex 'php7.0-mcrypt'
> E: Unable to locate package php7.0-readline
> E: Couldn't find any package by glob 'php7.0-readline'
> E: Couldn't find any package by regex 'php7.0-readline'
> E: Package 'php7.0-common' has no installation candidate
> E: Unable to locate package php7.0-recode
> E: Couldn't find any package by glob 'php7.0-recode'
> E: Couldn't find any package by regex 'php7.0-recode'
> E: Unable to locate package php7.0-mysql
> E: Couldn't find any package by glob 'php7.0-mysql'
> E: Couldn't find any package by regex 'php7.0-mysql'
> E: Unable to locate package php7.0-cli
> E: Couldn't find any package by glob 'php7.0-cli'
> E: Couldn't find any package by regex 'php7.0-cli'
> E: Unable to locate package php7.0-curl
> E: Couldn't find any package by glob 'php7.0-curl'
> E: Couldn't find any package by regex 'php7.0-curl'
> E: Unable to locate package php7.0-mbstring
> E: Couldn't find any package by glob 'php7.0-mbstring'
> E: Couldn't find any package by regex 'php7.0-mbstring'
> E: Unable to locate package php7.0-bcmath
> E: Couldn't find any package by glob 'php7.0-bcmath'
> E: Couldn't find any package by regex 'php7.0-bcmath'
> E: Unable to locate package php7.0-mysql
> E: Couldn't find any package by glob 'php7.0-mysql'
> E: Couldn't find any package by regex 'php7.0-mysql'
> E: Unable to locate package php7.0-opcache
> E: Couldn't find any package by glob 'php7.0-opcache'
> E: Couldn't find any package by regex 'php7.0-opcache'
> E: Unable to locate package php7.0-zip
> E: Couldn't find any package by glob 'php7.0-zip'
> E: Couldn't find any package by regex 'php7.0-zip'
> E: Unable to locate package php7.0-xml
> E: Couldn't find any package by glob 'php7.0-xml'
> E: Couldn't find any package by regex 'php7.0-xml'
> E: Unable to locate package php7.0-soap
> E: Couldn't find any package by glob 'php7.0-soap'
> E: Couldn't find any package by regex 'php7.0-soap'
> Some php.ini tweaks
> sed: can't read /etc/php/7.0/fpm/php.ini: No such file or directory
> sed: can't read /etc/php/7.0/fpm/php.ini: No such file or directory
> sed: can't read /etc/php/7.0/fpm/php.ini: No such file or directory
> sed: can't read /etc/php/7.0/fpm/php.ini: No such file or directory
> sed: can't read /etc/php/7.0/fpm/php.ini: No such file or directory
> sed: can't read /etc/php/7.0/fpm/pool.d/www.conf: No such file or directory
> sed: can't read /etc/php/7.0/fpm/php.ini: No such file or directory
> sed: can't read /etc/php/7.0/fpm/php.ini: No such file or directory
> sed: can't read /etc/php/7.0/fpm/php.ini: No such file or directory
> sed: can't read /etc/php/7.0/fpm/php.ini: No such file or directory
> sed: can't read /etc/php/7.0/fpm/php.ini: No such file or directory
> sed: can't read /etc/php/7.0/fpm/php.ini: No such file or directory
> sed: can't read /etc/php/7.0/fpm/php.ini: No such file or directory
> Failed to restart php7.0-fpm.service: Unit php7.0-fpm.service not found.
> Instaling MariaDB
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package php7.0-mysql
> E: Couldn't find any package by glob 'php7.0-mysql'
> E: Couldn't find any package by regex 'php7.0-mysql'
> Failed to restart php7.0-fpm.service: Unit php7.0-fpm.service not found.
> sudo: mysql_secure_installation: command not found
> nc_fresh_install.sh: line 79: mysql: command not found
> Here is the database
> Database:   XXXXXXXX
> Username:   XXXXXXXX
> Password:   XXXXXXXX

**Comment by bajpangosh** [comment]
Please use script https://github.com/bajpangosh/Nextcloud-With-Cloudflare-SSL-Easy-Install-script/tree/master/ubuntu-18.04

`wget -qO nc-18-04 run.kloudboy.com/nc-18-04 && sudo bash nc-18-04`

Use only on Ubuntu-18.04 and it must be Fresh droplet.
